modLoader="javafml"
loaderVersion="[30,)"
[[mods]]
modId="stone_age"
version="${file.jarVersion}"
displayName="Stone Age"
logoFile="stone_age.png"
authors="Yanny"

description='''
Stone Age gives you feeling of man from stone age. No more magically created planks from wood logs, the way to first crafting table is long and dangerous.
'''

[[dependencies.stone_age]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stone_age]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.stone_age]]
    modId="ages_api"
    mandatory=true
    versionRange="[1.15.2-1.2.0,)"
    ordering="NONE"
    side="BOTH"
